In [22]:
# Import pandas and numpy
import pandas as pd
import numpy as np

In [23]:
path = "dataset/dataset.csv" # Sesuaikan dengan lokasi file dataset.csv
df_epl = pd.read_csv(path)

apakah_ada_nilai_null_df = df_epl.isnull().values.any()

# Mengecek apakah terdapat nilai null di kolom tertentu, contohnya kolom "High"
apakah_ada_nilai_null_high = df_epl["goals"].isnull().values.any()

# Mencetak hasil pengecekan
print(f"Apakah terdapat nilai null di dataframe? {apakah_ada_nilai_null_df}")
print(f"Apakah terdapat nilai null di kolom Goals? {apakah_ada_nilai_null_high}")

Apakah terdapat nilai null di dataframe? False
Apakah terdapat nilai null di kolom Goals? False

In [24]:
df_epl.head()

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796